config:
  selfUrl: # https://saas.demotuan6.dev
  corsOrigins: https://demotuan6-st-gateway-web,https://demotuan6-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://demotuan6-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.demotuan6.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.demotuan6.dev
  tlsSecret: demotuan6-tls

image:
  repository: mycompanyname/demotuan6-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      