config:
  selfUrl: # https://gateway-public.demotuan6.dev
  corsOrigins: # https://demotuan6-st-gateway-web,https://demotuan6-st-gateway-public-web
  authServer:
    authority: # http://demotuan6-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.demotuan6.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #

reRoutes:
  accountService:
    url: http://demotuan6-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://demotuan6-st-administration
  productService:
    url: http://demotuan6-st-product

ingress:
  host: gateway-public.demotuan6.dev
  tlsSecret: demotuan6-tls

image:
  repository: mycompanyname/demotuan6-gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    