config:
  selfUrl: # https://product.demotuan6.dev
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://demotuan6-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.demotuan6.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: product.demotuan6.dev
  tlsSecret: demotuan6-tls

image:
  repository: mycompanyname/demotuan6-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      